#!/bin/bash

export IMAGE_NAME=ansgarschulte/heytech_rest_server:$TRAVIS_COMMIT
export LATEST=ansgarschulte/heytech_rest_server:latest

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker build -t $IMAGE_NAME .
docker push $IMAGE_NAME

docker build -t $LATEST .
docker push $LATEST